# Generated by Django 4.1.6 on 2023-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=30)),
                ('Room', models.TextField(default='Not Given', max_length=15)),
                ('Done', models.BooleanField(default=False)),
                ('Place', models.CharField(default='Not Given', max_length=10)),
                ('comments', models.TextField(max_length=200)),
                ('Cleaning_DateTime', models.DateTimeField()),
            ],
        ),
    ]
