# Generated by Django 4.1.6 on 2023-03-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaning_request',
            old_name='username',
            new_name='User_Name',
        ),
    ]
