# Generated by Django 4.1.6 on 2023-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_class',
            name='designation',
            field=models.CharField(choices=[('Student', 'Student'), ('Hall Manager', 'Hall Manager'), ('Mess Manager', 'Mess Manager'), ('Canteen Manager', 'Canteen Manager'), ('Sports Secy', 'Sports Secy')], max_length=15),
        ),
    ]
