# Generated by Django 4.1.7 on 2023-03-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('Cricket', 'Cricket'), ('Table Tennis', 'Table Tennis'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Hockey', 'Hockey'), ('Football', 'Football')], default='Cricket', max_length=100)),
                ('day_of_booking', models.DateField()),
                ('time_of_checkin', models.TimeField()),
                ('time_of_checkout', models.TimeField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guestroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=1)),
                ('status', models.CharField(choices=[('book', 'Book'), ('unavailable', 'Item is Booked')], max_length=100)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('price', models.CharField(max_length=100)),
                ('manager_validation', models.CharField(default='NO', max_length=10)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sports_equipments_registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipments', models.CharField(choices=[('CB', 'Cricket Bat'), ('TT', 'Table Tennis'), ('BM', 'Badminton'), ('BB', 'Basketball'), ('HK', 'Hockey'), ('FB', 'Football')], default='CB', max_length=2)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sports_equipments_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_selected', models.CharField(choices=[('CB', 'Cricket Bat'), ('TT', 'Table Tennis'), ('BM', 'Badminton'), ('BB', 'Basketball'), ('HK', 'Hockey'), ('FB', 'Football')], default='CB', max_length=100)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('argument', models.CharField(default='Default_value', max_length=150)),
                ('secy_validation', models.CharField(default='NO', max_length=10)),
                ('student_return_request', models.CharField(default='NO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sports_equipmnents_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipments_store', models.CharField(choices=[('CB', 'Cricket Bat'), ('TT', 'Table Tennis'), ('BM', 'Badminton'), ('BB', 'Basketball'), ('HK', 'Hockey'), ('FB', 'Football')], default='CB', max_length=2)),
                ('quantity_store', models.IntegerField()),
            ],
        ),
    ]
